// The project list. It feeds three places at build time:
//
//   /work.html            the full list plus the hover preview
//   /index.html           the first three, as cards
//   /work/<slug>.html     one case study per entry, generated by case.page.js
//
// Add an entry here and its case page appears on the next build. `shot`,
// `heroShot`, `wideShot`, `tiles` and `strip` are the captions of the
// placeholder frames — replace each one with a real image when you have it.

const projects = [
  {
    name: "Vantablack",
    client: "Competitive esport organisation",
    kind: "Identity + website",
    year: "2026",
    duration: "9 weeks",
    shot: "team page, dark layout",
    summary:
      "A roster of eleven players across three games, all sharing one wordmark that had to survive being embroidered, streamed and printed.",
    context:
      "Vantablack signed two new rosters in six months and had no visual system to hold them together — every announcement graphic was made from scratch by a different volunteer. The studio built one identity and one site that anyone on the staff can publish into without breaking it.",
    reasons: [
      {
        title: "One mark, three states",
        body:
          "The wordmark is drawn once and cut down to a monogram and a single glyph. Each state has a minimum size written into the guidelines, so a jersey patch and a stream avatar use the same drawing rather than two unrelated logos.",
      },
      {
        title: "Weight instead of colour",
        body:
          "Esport brands drown in gradients and neon. Hierarchy here comes from weight contrast — a black display cut against a light text weight — so the palette stays at one accent and everything reads at a glance in a chat sidebar.",
      },
      {
        title: "A roster page that stays true",
        body:
          "Player cards pull from a single data file. Signing or releasing a player is one line of text, which is why the page is still accurate eight months after launch.",
      },
      {
        title: "Built for volunteers",
        body:
          "The announcement templates ship as three fixed layouts with locked type sizes. Staff choose a layout and drop in a photo; there is no way to accidentally stretch the logo.",
      },
    ],
    deliverables: [
      "Wordmark, monogram and glyph, with usage guidelines",
      "Type and colour system, one accent",
      "Eight-page static website, no build step",
      "Announcement template pack for social",
      "Stream overlay and lower-third set",
    ],
    heroShot: "home page, full width",
    wideShot: "roster page, desktop",
    tiles: ["logo lockup, dark and light", "mark construction grid"],
    strip: [
      "mobile roster screen",
      "type specimen sheet",
      "jersey and overlay pack",
    ],
  },
  {
    name: "Kōra",
    client: "Independent game studio",
    kind: "Visual identity",
    year: "2025",
    duration: "5 weeks",
    shot: "logo on press kit",
    summary:
      "A two-person studio shipping its first title needed an identity that would not be mistaken for its own game's artwork.",
    context:
      "Kōra's first game had a finished art direction; the studio behind it had none, and press kept lifting in-game screenshots as the company logo. The identity deliberately steps away from the game so the studio can ship a second, different title without a rebrand.",
    reasons: [
      {
        title: "The studio is not the game",
        body:
          "The identity uses no illustration and none of the game's palette. It is a wordmark, a grid and two weights, which lets the games be loud while the studio stays quiet behind them.",
      },
      {
        title: "Press kit first",
        body:
          "The first artefact designed was the press kit page, because that is where every journalist meets the studio. Everything else was derived from what that page needed.",
      },
      {
        title: "Two weights, no more",
        body:
          "A light text weight and a black display weight cover every case from a storefront page to a business card. Fewer weights means fewer decisions for two people with no designer on staff.",
      },
    ],
    deliverables: [
      "Wordmark and monogram",
      "Type and colour system",
      "Press kit page template",
      "Storefront asset set",
    ],
    heroShot: "wordmark, large",
    wideShot: "press kit spread",
    tiles: ["wordmark, two weights", "monogram construction"],
    strip: [
      "business card, front and back",
      "storefront capsule art",
      "type specimen sheet",
    ],
  },
  {
    name: "Halcyon",
    client: "Streamer community",
    kind: "Website",
    year: "2025",
    duration: "4 weeks",
    shot: "schedule page",
    summary:
      "A 40,000-member community whose links lived in six different pinned messages, collected into one page that loads instantly.",
    context:
      "Everything the community needed — schedule, rules, VOD archive, merch — was scattered across pinned messages. One static site replaced all of them and now sits in the channel topic.",
    reasons: [
      {
        title: "One page, no scroll trap",
        body:
          "The schedule sits above everything else because it is the only thing most visitors came for. Archive and merch are one click below it, not buried in a menu.",
      },
      {
        title: "Fast on a phone on mobile data",
        body:
          "No framework, no fonts beyond one family, no images above 80 kb. The page is usable before a spinner would have finished a first turn.",
      },
    ],
    deliverables: [
      "Five-page static site",
      "Schedule and VOD components",
      "Dark theme matched to the community's chat",
    ],
    heroShot: "home page, mobile and desktop",
    wideShot: "VOD archive grid",
    tiles: ["schedule module, week view", "rules page"],
    strip: ["mobile home screen", "merch page", "VOD detail"],
  },
];

/** "Kōra" -> "kora". Strips accents so the URL stays ASCII. */
function slugify(name) {
  return name
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/** 0 -> "01". The numbering used down the left of every list on the site. */
function ordinal(index) {
  return String(index + 1).padStart(2, "0");
}

// Everything the templates need is precomputed here, so the templates stay
// free of logic. `next` is stored as two plain fields rather than a reference
// to the next project, to keep this data serialisable.
export default projects.map((project, index) => {
  const next = projects[(index + 1) % projects.length];

  return {
    ...project,
    slug: slugify(project.name),
    num: ordinal(index),
    url: `/work/${slugify(project.name)}.html`,
    reasons: project.reasons.map((reason, i) => ({
      ...reason,
      num: ordinal(i),
    })),
    deliverables: project.deliverables.map((label, i) => ({
      label,
      num: ordinal(i),
    })),
    nextName: next.name,
    nextUrl: `/work/${slugify(next.name)}.html`,
  };
});
