// The project list. It feeds three places at build time:
//
//   /work.html            the full list plus the hover preview
//   /index.html           the first three, as cards
//   /work/<slug>.html     one case study per entry, generated by case.page.js
//
// Add an entry here and its case page appears on the next build.
//
// Screenshots live in src/public/shots as lossless WebP. Each one carries its
// own `ratio` ("width/height") so the browser reserves the right box before
// the image arrives and nothing shifts on load.
//
// `stage` is the presentation around a screenshot: the colour it is matted
// on, the frame border and the drop shadow. It is per project, because a
// dark web app and a white desktop app do not sit well on the same backdrop.

const projects = [
  {
    name: "Nocturea",
    client: "Nocturea — in-house",
    kind: "Identity + website",
    year: "2026",
    duration: "In-house, ongoing",
    summary:
      "The studio's own first site: a twelve-page static build that ships zero JavaScript and presents five services as a Minecraft-style module grid.",
    context:
      "Nocturea builds, hosts and designs Minecraft experiences, and its own site had grown into twelve hand-maintained HTML files with the nav and footer copy-pasted into every one of them. The rebuild moved the whole thing onto Lume and Deno: content in one file per page, nav, footer and copyright in a single shared data file, and a production output that is nothing but static files behind nginx.",
    image: "/public/shots/nocturea-v1-home.webp",
    imageRatio: "909/909",
    hero: {
      src: "/public/shots/nocturea-v1-home.webp",
      ratio: "909/909",
      url: "nocturea.com",
    },
    stage: {
      bg: "#0f0f11",
      shadow: "0 40px 120px rgba(0, 0, 0, .6)",
      border: "1px solid #1e1e21",
    },
    reasons: [
      {
        title: "Zero JavaScript, on purpose",
        body:
          "Nothing on the site needs a runtime, so nothing ships one. The build outputs plain HTML and one stylesheet; every page is interactive the moment it arrives, which matters for an audience reaching it from a Discord link on mobile data.",
      },
      {
        title: "Services as a module grid",
        body:
          "The five services — Boost, Design, Hosting, Team, Web — read as numbered slots in a six-cell grid, with the sixth left dimmed and marked SOON. The vocabulary comes from the game the clients play, so the offer explains itself before a word of copy is read.",
      },
      {
        title: "Green in the dark",
        body:
          "The mark is a single green form on near-black, and that green is the only accent in the system. Space Grotesk carries the display and JetBrains Mono handles labels and section headers, which gives the terminal register the brand leans on without any decorative artwork.",
      },
      {
        title: "URLs kept exactly as they were",
        body:
          "Pretty URLs are deliberately switched off, so pages still build to /about.html rather than /about/. The migration changed how the site is made and not one inbound link or the ranking attached to it.",
      },
      {
        title: "One place to edit",
        body:
          "Nav, footer links and the copyright line live in a single data file instead of twelve copies. Adding a page is a front-matter block and a body; the shell takes care of head tags, OG image and the active nav state.",
      },
    ],
    deliverables: [
      "Mark and dark-mode visual system, one accent",
      "Type system: Space Grotesk and JetBrains Mono",
      "Twelve-page static site on Lume and Deno",
      "Shared layout with per-page front matter",
      "nginx deployment config with caching and 404 handling",
    ],
    tiles: [
      {
        label: "mark on near-black",
        src: "/public/shots/v1-tile-mark.webp",
        ratio: "1/1",
        bg: "#0f0f11",
      },
      {
        label: "module grid, six slots",
        src: "/public/shots/v1-tile-modules-grid.webp",
        ratio: "848/352",
        bg: "#0f0f11",
      },
    ],
    gallery: [
      {
        label: "Design service page",
        src: "/public/shots/v1-page-design.webp",
        ratio: "708/887",
        url: "nocturea.com/design.html",
        bg: "#0f0f11",
        raised: false,
      },
      {
        label: "About",
        src: "/public/shots/v1-page-about.webp",
        ratio: "531/501",
        url: "nocturea.com/about.html",
        bg: "#0f0f11",
        raised: true,
      },
      {
        label: "FAQ",
        src: "/public/shots/v1-page-faq.webp",
        ratio: "590/489",
        url: "nocturea.com/faq.html",
        bg: "#0f0f11",
        raised: false,
      },
      {
        label: "Contact",
        src: "/public/shots/v1-page-contact.webp",
        ratio: "649/480",
        url: "nocturea.com/contact.html",
        bg: "#0f0f11",
        raised: true,
      },
    ],
  },
  {
    name: "MontLivre",
    client: "In-house",
    kind: "Desktop reading app",
    year: "2026",
    duration: "In-house, ongoing",
    summary:
      "A Windows e-book reader rebuilt from a 122 MB Electron app into a 4.16 MB Tauri shell, with a Swiss-poster interface that stops at the edge of the page you read.",
    context:
      "Version 1 was 6,926 lines of Electron carrying its own layout engine and a 122 MB installer. Version 2 hands reading to foliate-js and the shell to Tauri 2, which rides the WebView2 already on every Windows machine: 3,626 lines, a 4.16 MB installer, around 30 MB of memory at rest. It reads EPUB, MOBI, AZW3, FB2 and CBZ, works offline, asks for no account and sends nothing anywhere.",
    // Cut to the preview's own 4/3 rather than letting CSS crop the window
    // capture: the library grid runs past the bottom of that capture, so any
    // crop of it slices a row of covers. This one ends on a clean line after
    // the first row, with the app's own background extended to fill 4/3.
    image: "/public/shots/ml-page-library-4x3.webp",
    imageRatio: "840/630",
    hero: {
      src: "/public/shots/ml-page-library.webp",
      ratio: "838/540",
      url: "MontLivre 2.3.5 — Bibliothèque",
    },
    stage: {
      bg: "#e1e1e1",
      shadow: "18px 18px 0 #000000",
      border: "1px solid #000000",
    },
    reasons: [
      {
        title: "Three rules hold the whole interface",
        body:
          "No rounded corners, no blurred shadows, one bright colour on screen at a time. Shadows are solid offsets, rules are hairlines, and the palette — Yolk, Ochre, Violet, Moss on Coal, Ash and Cloud — never runs two accents at once. The result is a typographic poster you can operate.",
      },
      {
        title: "The reading page gets none of it",
        body:
          "Every decoration stops at the chrome. The page itself is a serif on paper: no accent, no shadow, no shape. The interface is allowed a personality precisely because the book is not asked to share it.",
      },
      {
        title: "Covers are generated, not defaulted",
        body:
          "A book with no cover does not get a grey rectangle. Colour, shape and tilt come from a hash of the title, so the poster is stable across launches and no two neighbours look alike — the shelf reads as a shelf rather than a spreadsheet.",
      },
      {
        title: "Resume that survives a change of type size",
        body:
          "Position is stored as a CFI, not a scroll offset. Change the text size, the margins or the number of pages, and the book still opens exactly where it was left.",
      },
      {
        title: "No bundler, no Node",
        body:
          "The front end is HTML, CSS and native ES modules served as they are written; the only toolchain is Rust. Nothing between the source and the running app means nothing to debug between them either.",
      },
      {
        title: "The front end holds no keys",
        body:
          "It has no filesystem permission at all. It passes identifiers, and store.rs turns them into paths under the application data folder — imported books are copied there rather than referenced in place.",
      },
    ],
    deliverables: [
      "Visual system: Archivo display, Literata for reading, four accents",
      "Y2K shape set and square-cut icon set, inline SVG",
      "Four screens: library, reader, annotations, settings",
      "Generated cover system, hashed from the title",
      "Tauri 2 shell, signed in-app updates, 4.16 MB installer",
    ],
    tiles: [
      {
        label: "generated covers, hashed from the title",
        src: "/public/shots/ml-detail-covers.webp",
        ratio: "760/520",
        bg: "#e1e1e1",
      },
      {
        label: "highlight in ochre, on paper",
        src: "/public/shots/ml-detail-highlight.webp",
        ratio: "760/520",
        bg: "#000000",
      },
    ],
    gallery: [
      {
        label: "Reader",
        src: "/public/shots/ml-page-reader.webp",
        ratio: "838/540",
        url: "MontLivre — Lecture",
        bg: "#ff5500",
        raised: false,
      },
      {
        label: "Annotations",
        src: "/public/shots/ml-page-notes.webp",
        ratio: "838/540",
        url: "MontLivre — Annotations",
        bg: "#e1e1e1",
        raised: true,
      },
      {
        label: "Settings",
        src: "/public/shots/ml-page-settings.webp",
        ratio: "838/540",
        url: "MontLivre — Réglages",
        bg: "#7d00ff",
        raised: false,
      },
    ],
  },
  {
    name: "CNRS//FLUX",
    client: "In-house",
    kind: "News aggregator",
    year: "2026",
    duration: "In-house, ongoing",
    summary:
      "A scientific-news aggregator that collects 44 public RSS feeds from 16 French research organisations every thirty minutes and makes them searchable in one dark terminal-like console.",
    context:
      "Research news in France is scattered across dozens of institutional feeds — CNRS institutes and regional delegations, Inserm, Inria, CEA, CERN, ESA, IRD and a handful of science media — each with its own site and none with a shared index. CNRS//FLUX collects all of them on a thirty-minute schedule, deduplicates and indexes them in Deno KV, and serves one searchable feed. The whole stack is Deno: Fresh for server rendering and islands, Hono for the API, Deno KV for storage, Deno.cron for the collection.",
    image: "/public/shots/cf-page-home.webp",
    imageRatio: "909/1475",
    hero: {
      src: "/public/shots/cf-page-home.webp",
      ratio: "909/1475",
      url: "cnrs-flux.simon256px.deno.net",
    },
    stage: {
      bg: "#0a100c",
      shadow: "0 40px 120px rgba(0, 0, 0, .65)",
      border: "1px solid #1a2b1f",
    },
    reasons: [
      {
        title: "A scientific terminal, not a news portal",
        body:
          "Near-black tinted green, phosphor green, IBM Plex Mono for anything that is data — badges, telemetry, filters — and Space Grotesk for anything that is meaning. A background grid and small + registration marks hold the page together. The interface looks like the instruments the news comes from.",
      },
      {
        title: "Articles without an image still get a face",
        body:
          "Feeds are inconsistent about images. Rather than a grey box, a missing visual becomes a typographic tile: an outlined index number, the source kind, and a dotted field. The grid keeps its rhythm whatever the feeds send.",
      },
      {
        title: "Colour carries the source type",
        body:
          "Each kind of source has its own pip colour — white for national, cyan for media, green for institutes, yellow for regional delegations. Reading provenance takes no legend and no second line of text.",
      },
      {
        title: "Server-rendered first, interactive after",
        body:
          "The first 24 articles come straight out of Deno KV during server rendering. The API is only queried once a filter changes, with debounced search and cancellable requests, so the page is useful before any JavaScript runs.",
      },
      {
        title: "Deduplication belongs in the key",
        body:
          "The primary key is a SHA-256 hash of the item's guid or link, and inserts are atomic, so re-reading a feed cannot create a second copy. Date-ordered keys give reverse-chronological traversal for free.",
      },
      {
        title: "One registry to extend the network",
        body:
          "Adding a feed is one entry in sources.ts — collector, API and filters pick it up on their own. The Sources dashboard then shows its collection status next to the others, error state included.",
      },
    ],
    deliverables: [
      "Dark terminal design system, self-hosted type, no front-end dependency",
      "Article card with typographic fallback tile",
      "Search console: full-text query, five facets, debounced",
      "Sources dashboard: 44 feeds, collection status and volumes",
      "Hono API: articles, sources, stats, manual collection",
    ],
    tiles: [
      {
        label: "article card, typographic tile",
        src: "/public/shots/cf-detail-card.webp",
        ratio: "760/520",
        bg: "#0a100c",
      },
      {
        label: "search console, five facets",
        src: "/public/shots/cf-detail-console2.webp",
        ratio: "760/330",
        bg: "#0a100c",
      },
    ],
    gallery: [
      {
        label: "Sources dashboard",
        src: "/public/shots/cf-page-sources.webp",
        ratio: "909/937",
        url: "cnrs-flux.simon256px.deno.net/sources",
        bg: "#0a100c",
        raised: false,
      },
    ],
  },
  {
    name: "Nocturea Identity",
    client: "Nocturea — in-house",
    kind: "Mark and guidelines",
    year: "2026",
    duration: "In-house, ongoing",
    summary:
      "The studio's own mark, drawn from a single 68-unit module: a dome, a quarter and a spark, with the grid, clearspace and minimum sizes written down.",
    context:
      "The mark existed before anything was written about it, which meant every new use re-decided its size and its margins. This is the drawing put back on its grid and the rules set down: one module and one inscribed radius generate every edge, the clearspace is derived from the mark's own width rather than picked, and there is one stated point — 24 px — below which the spark is dropped instead of being allowed to fill in.",
    // Vector plates rather than screenshots, and no window chrome around
    // them: these are drawings, not screens.
    framed: false,
    // Every plate is text-free on purpose. The wording is carried by the
    // page's captions, so it is set in the site's own Archivo.
    image: "/public/shots/noc-id-mark.svg",
    imageRatio: "1200/900",
    hero: {
      src: "/public/shots/noc-id-mark.svg",
      ratio: "1200/900",
      alt: "the mark on midnight",
    },
    stage: {
      bg: "#14120f",
      shadow: "none",
      border: "1px solid rgba(234, 231, 226, .14)",
    },
    reasons: [
      {
        title: "One module generates every edge",
        body:
          "A 68-unit square and the R34 circle inscribed in it produce the dome, the ground line and the quadrant. Nothing in the mark is placed by eye, so it can be redrawn at any size from the two numbers rather than from a traced file.",
      },
      {
        title: "Three parts, each doing one job",
        body:
          "The dome is the night sky flattened to a half circle at the horizon. The quarter is the ground, and taking only one of the four keeps the mark asymmetric so it never reads as a generic roundel. The spark sits in the empty quadrant and sets the optical centre.",
      },
      {
        title: "Clearspace derived, not chosen",
        body:
          "The margin is a quarter of the mark's width on every side. Because it scales with the drawing, the rule holds on a favicon and on a wall without anyone converting it into pixels first.",
      },
      {
        title: "A stated floor, and what gives way at it",
        body:
          "Below 24 px the spark's concave curves fill in and the mark turns to mud, so the guideline drops the spark rather than letting it degrade. The dome and quarter alone still read as the same brand.",
      },
      {
        title: "Four colours, one of them warm",
        body:
          "Midnight, Bone and Slate carry the system; Lamplight is the single warm note and is reserved for accents, never for the mark itself. Holding the mark to Bone or Midnight is what lets it invert cleanly onto any of the others.",
      },
    ],
    deliverables: [
      "Mark as vector, with its construction grid",
      "Component breakdown: dome, quarter, spark",
      "Clearspace and minimum-size rules",
      "Reduced form for use below 24 px",
      "Four-colour palette with reversal pairs",
    ],
    tiles: [
      {
        label: "one module, one inscribed radius",
        src: "/public/shots/noc-id-construction.svg",
        ratio: "1000/1000",
        bg: "#14120f",
      },
      {
        label: "clearspace, a quarter of the mark width",
        src: "/public/shots/noc-id-clearspace.svg",
        ratio: "1000/1000",
        bg: "#14120f",
      },
    ],
    gallery: [
      {
        label: "The dome, the quarter, the spark",
        src: "/public/shots/noc-id-anatomy.svg",
        ratio: "1200/420",
        bg: "#14120f",
        raised: false,
      },
      {
        label: "120, 56 and 24 px — the last without its spark",
        src: "/public/shots/noc-id-scale.svg",
        ratio: "1200/420",
        bg: "#14120f",
        raised: true,
      },
      {
        label: "Midnight, Bone, Lamplight, Slate",
        src: "/public/shots/noc-id-palette.svg",
        ratio: "1200/420",
        bg: "#14120f",
        raised: false,
      },
      {
        label: "Reversed: bone on slate, midnight on bone",
        src: "/public/shots/noc-id-applied.svg",
        ratio: "1200/600",
        bg: "#14120f",
        raised: true,
      },
    ],
  },
];

/** "CNRS//FLUX" -> "cnrs-flux", "Ren'ai" -> "renai". ASCII only. */
function slugify(name) {
  return name
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .toLowerCase()
    // Apostrophes close a word rather than break it: pops, not pop-s.
    .replace(/['’]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/** 0 -> "01". The numbering used down the left of every list on the site. */
function ordinal(index) {
  return String(index + 1).padStart(2, "0");
}

/** "909/1475" -> {w: 909, h: 1475}, so <img> can carry width and height. */
function dimensions(ratio) {
  const [w, h] = String(ratio).split("/").map(Number);
  return { w, h };
}

/** The shape of the preview box on /work.html. */
const PREVIEW_RATIO = 4 / 3;

// Everything the templates need is precomputed here, so the templates stay
// free of logic. `next` is stored as plain fields rather than a reference to
// the next project, to keep this data serialisable.
export default projects.map((project, index) => {
  const next = projects[(index + 1) % projects.length];
  const shot = dimensions(project.imageRatio);

  return {
    ...project,
    slug: slugify(project.name),
    num: ordinal(index),
    url: `/work/${slugify(project.name)}.html`,
    // Screens get the window chrome; photography opts out with framed: false.
    framed: project.framed !== false,
    image: {
      src: project.image,
      ...shot,
      // Every preview is shown in the same 4/3 box. Cropping to it would cut
      // the left and right edges off a wider screenshot, so those are fitted
      // whole and the spare height is matted in the project's stage colour.
      // Square and tall ones are cropped from the top instead, where the head
      // of a page or an app window is.
      fit: shot.w / shot.h > PREVIEW_RATIO ? "contain" : "cover",
      // Where a cropped preview takes its window from. The head of a page is
      // at the top; a photograph usually has its subject lower.
      position: project.imagePosition ?? "top center",
    },
    hero: { ...project.hero, ...dimensions(project.hero.ratio) },
    tiles: project.tiles.map((tile) => ({
      ...tile,
      ...dimensions(tile.ratio),
    })),
    gallery: project.gallery.map((item) => ({
      ...item,
      ...dimensions(item.ratio),
      framed: (item.framed ?? project.framed) !== false,
    })),
    // One column reads better than a lonely half-width figure.
    galleryWide: project.gallery.length === 1,
    reasons: project.reasons.map((reason, i) => ({
      ...reason,
      num: ordinal(i),
    })),
    deliverables: project.deliverables.map((label, i) => ({
      label,
      num: ordinal(i),
    })),
    nextName: next.name,
    nextUrl: `/work/${slugify(next.name)}.html`,
  };
});
